name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
    -
        name: Build docker image without pushing it
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: scraper:latest

